### PR TITLE
Bump puppeteer version

### LINKED ISSUE #204: Extracted CSS in v1.1.3 is very different from that extracted in v1.1.2 usign local file in url parameter(file://)
I'm having very different results after update to v1.1.3. The generated file is considerably different and smaller.

I also noticed is the screenshot can not parse HTML when the url parameter contains a file (file: //)

Below, we have the result of the screenshot of the same code using different versions of the Penthouse.

My Node version is v6.10.3

in v1.1.2
screenshot-v1-1-2

in v1.1.3
screenshot-v1-1-3

### LINKED ISSUE #226: puppeteer@1.0 upgrade
Test & update puppeteer to the released 1.0 version

### PR DESCRIPTION
**Pull request by Saturate**
This new version supports the `file://` again without bugs.

Tested puppeteer directly on win8.1 and win10.

I can't run the unit tests, on my machine, so let's see what the CI says.

Fixes #226 
Closes #204

### CODE REVIEW

**Comment by pocketjoso** [comment]
Yep, thanks for the PR! As long as the tests pass I will indeed merge and release a new version - it's about time!

What exactly happens when you try to run the unit tests? Could be nice to open another issue for this, to work on long term.

**Comment by pocketjoso** [comment]
@Saturate the tests are failing just because `puppeteer` changed an API:
>     TypeError: page.setRequestInterceptionEnabled is not a function

**Comment by Saturate** [comment]
Ah, yes. Last time we did something like this, that API thing was changed as well - I'll look into it.

The unit test says the following on windows 10:

```
PS F:\Work\GitHub\penthouse> npm test

> penthouse@1.4.0 test F:\Work\GitHub\penthouse
> jest test/core.test.js

 FAIL  test\core.test.js
  penthouse core tests
    × encountered a declaration exception (12ms)

  ● penthouse core tests › encountered a declaration exception

    TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string

       6 | describe('penthouse core tests', () => {
       7 |   function staticServerFileUrl (file) {
    >  8 |     return 'file://' + path.join(process.env.PWD, 'test', 'static-server', file)
       9 |   }
      10 |   var page1FileUrl = staticServerFileUrl('page1.html')
      11 |

      at staticServerFileUrl (test/core.test.js:8:29)
      at Suite.Object.<anonymous>.describe (test/core.test.js:10:22)
      at Object.<anonymous> (test/core.test.js:6:1)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.691s, estimated 2s
Ran all test suites matching /test\\core.test.js/i.
npm ERR! Test failed.  See above for more details.
```

I'll look into this as well, and maybe we should put a build up on appveyor as well for windows?

**Comment by pocketjoso** [comment]
Regarding windows - don't attempt to fix it in this PR, it's too much. Yes Appveyor would be a good idea but first there's a bunch of fixes needed. In this particular test it might just be something like the `process.env.PWD`, but there are other tests that I know are hacky and just cannot support windows in their current format.. so if you want to discuss windows support I would advise opening up an issue and talking about it a bit more in detail before diving in to more work.

**Comment by pocketjoso** [comment]
Hmm looks like something else might have changed in the latest Puppeteer version(s)... I will have to look into it, but not sure I will have time today. Will get back to you (unless you can find the issue, but could be a bit difficult).

**Comment by Saturate** [comment]
Yikes! There's a lot of changes it seems.

And with no windows it's a bit hard for me to look at, without a lot of extra work.
I'll create a issue at some point about windows support, and maybe create a PR.

Would be nice to get it working for all platforms.

**Comment by pocketjoso** [comment]
So testing this further...

❌ `Puppeteer@0.13.0` broke Penthouse due to the `file://` protocol issue.
✅ `Puppeteer@1.0.0` made it work again
❌ `Puppeteer@1.1.0` fail again (still due to `file://`? unconfirmed)
❌ `Puppeteer@1.1.1` same..

**Comment by pocketjoso** [comment]
Just tested and still broken in Puppeteer 1.2 :/

**Comment by Saturate** [comment]
What a diehard bug, hope it's fixed soon or I'll have to greate a hashtag campaign on twitter :-)

**Comment by pocketjoso** [comment]
Final upgrade of Puppeteer to latest version now merged and published in Penthouse@1.4.5 (latest), via #261. Thanks for the PR and don't hesitate to help out again in the future, hopefully we don't have issues like these anymore. 👍

**Comment by Mateozmaldonado17** [comment]
Hi everyone, I'm in the 1.20.0 version of Puppeteer and I have this problem

**Comment by pocketjoso** [comment]
@Mateozmaldonado17 what exactly is your issue, and what's your setup? Are you using Penthouse, and at what version?

Could you please open a new issue to describe your issue?

**Comment by Mateozmaldonado17** [comment]
I am exaggeratedly looking for the solution to this error, I have a macbook pro 2018 and install puppeteer 1.20.0 to do Server Side Rendering, my application has 2 request, one a CSS and another one JS both are encapsulated by this html code:

1. request index.html, this has 2 important request one css and js.

main.css response:
<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;"> ... al code 
 css ... </pre></body></html>

main.js response:
<html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;"> ... al code javascript ... </pre></body></html>


and for obvious reasons in my browser this comes out:

webcomponents-loader.js:1 Uncaught SyntaxError: Unexpected token '<'
main.776595c9.js:1 Uncaught SyntaxError: Unexpected token '<'
